# Generated by Django 5.2.1 on 2025-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='scores',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
