# Generated by Django 5.2.1 on 2025-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_player_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
